dist: xenial

services:
  - mysql

language: python

sudo: false

git:
  depth: 1
  quiet: true

cache: pip

python:
 - "3.7"
 - "3.8"
 - "3.9"
 - "3.10-dev"

before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where user='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - touch .env

install:
  - 'pip install tox-travis codecov'

script: tox

notifications:
    slack:
      rooms:
        - pivotalenergy:SvNSkVaLVlZeu82utL37wSvy#travis



after_success:
  - coverage report
  - codecov -t dc2fe941-c3e2-4e48-a5fe-162755a30c6c
